server:
  port: 6767
  ip: 127.0.0.1
spring:
  jackson:
    time-zone: Asia/Shanghai
  profiles: local

eureka:
  client:
    service-url:
      defaultZone: http://root:admin123!@localhost:6761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}(${server.ip}):${server.port}
    appname: app-zuul

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:6161/me
      prefer-token-info: false

zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
  routes:
    uaa:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: app-user-server
    frontInterface:
      path: /frontInterface/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: app-front-interface-server
    backInterface:
      path: /backInterface/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: app-back-interface-server

ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000