server:
  port: 8000
  ip: 127.0.0.1
spring:
  jackson:
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务器地址
    gateway:
      routes:
        - id: user #路由ID，全局唯一
            uri: http://im-user-server #目标微服务的请求地址和端口
            predicates:
              - Path=/user/**  #路由条件，采用path路由规则
            filters:
              - StripPrefix=1
        - id: ws
           uri: lb:ws://im-websocket-server:8002
           predicates:
             - Path=/ws/**
           #filters:
             #- StripPrefix=1


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:6161/me
      prefer-token-info: false


ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000