server:
  port: 8002
  ip: 127.0.0.1

spring:
  jackson:
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务器地址
  redis:
    host: 192.168.85.47
    password: passwd123
    port: 6379
    #Redis数据库索引（默认为0）
    database: 1
    timeout: 5000
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 50
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 20000
      #连接池中的最大空闲连接
      max-idle: 20
      #连接池中的最小空闲连接
      min-idle: 2
  rabbitmq:
    host: 192.168.85.47
    username: admin
    password:  password
    port: 5672
    publisher-confirms: true
  datasource:
    master:
      url: jdbc:oracle:thin:@127.0.0.1:1521:xe
      username: m_order
      password: 123456
      driver-class-name: oracle.jdbc.OracleDriver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall,slf4j
      max-active: 100
      initial-size: 10
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

logging:
  level:
    root: debug
    sun: warn
    org.apache: warn


feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
