server:
  port: 8080



spring:
  thymeleaf:


  jackson:
    time-zone: Asia/Shanghai

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: 数据库用户名
    password: 数据库密码



#tis:
#  mapper-locations: classpath:mapper/**/*Mapper.xml
#  type-aliases-package: com.app.product.model
logging:
  level:
    com.im: debug

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMco rethodsArguments: true
  params: count=countSql
  returnPageInfo: check




